
import com.sun.glass.ui.Size;
import java.awt.Color;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class Home extends javax.swing.JFrame {
    private final Color Defaultcolor;
    private final Color Clickedcolor;
    
    
    registration reg=new registration();
     homein in=new homein();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
         pmain.add(in).setVisible(true);
    
        
        nonactive();
        
        Defaultcolor=new Color(225,221,221);
        Clickedcolor=new Color(198,141,112);
        
        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
        
     }
   

    public void nonactive(){
        pdashboad.setVisible(false);
        pdashboad.setEnabled(false);
        pmain.setVisible(true);
        
        ldash.setVisible(true);
        ldash.setEnabled(true);
        pmain.setSize(1000,942);
    }
     public void active(){
         pdashboad.setVisible(true);
         pdashboad.setEnabled(true);
         pmain.setVisible(true);
        
         ldash.setVisible(false);
         ldash.setEnabled(false);
         pmain.setSize(888,942);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ldash = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pmain = new javax.swing.JPanel();
        pdashboad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        phome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        preg = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        peditreg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ppar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        peditpar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pdoc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        peditdoc = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pacset = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pleave = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        peditlea = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        psearch = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(1270, 920, 1270, 920));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1270, 920));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 950));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ldash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ds.png"))); // NOI18N
        ldash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ldashMouseClicked(evt);
            }
        });
        getContentPane().add(ldash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(230, 225, 225));

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 40)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(55, 70, 89));
        jLabel18.setText("HOME OF HOPE");

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(29, 93, 96));
        jLabel17.setText("CHILDREN INFORMATIION ");

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(29, 93, 96));
        jLabel19.setText("MANAGEMENT SYSTEM");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19))
                            .addComponent(jLabel17))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 860, 180));

        pmain.setBackground(new java.awt.Color(230, 225, 225));

        javax.swing.GroupLayout pmainLayout = new javax.swing.GroupLayout(pmain);
        pmain.setLayout(pmainLayout);
        pmainLayout.setHorizontalGroup(
            pmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pmainLayout.setVerticalGroup(
            pmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        getContentPane().add(pmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 860, 660));

        pdashboad.setBackground(new java.awt.Color(225, 221, 221));
        pdashboad.setPreferredSize(new java.awt.Dimension(361, 805));
        pdashboad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("DASHBOAD");
        pdashboad.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        phome.setBackground(new java.awt.Color(225, 221, 221));
        phome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                phomeMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon8.png"))); // NOI18N
        jLabel2.setText("Home");

        javax.swing.GroupLayout phomeLayout = new javax.swing.GroupLayout(phome);
        phome.setLayout(phomeLayout);
        phomeLayout.setHorizontalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phomeLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        phomeLayout.setVerticalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phomeLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pdashboad.add(phome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 361, 50));

        preg.setBackground(new java.awt.Color(225, 221, 221));
        preg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pregMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pregMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon9.png"))); // NOI18N
        jLabel3.setText("Registration");

        javax.swing.GroupLayout pregLayout = new javax.swing.GroupLayout(preg);
        preg.setLayout(pregLayout);
        pregLayout.setHorizontalGroup(
            pregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel3)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        pregLayout.setVerticalGroup(
            pregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pdashboad.add(preg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 361, 50));

        peditreg.setBackground(new java.awt.Color(225, 221, 221));
        peditreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peditregMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                peditregMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon10.png"))); // NOI18N
        jLabel4.setText("Edit Info");

        javax.swing.GroupLayout peditregLayout = new javax.swing.GroupLayout(peditreg);
        peditreg.setLayout(peditregLayout);
        peditregLayout.setHorizontalGroup(
            peditregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peditregLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(88, 88, 88))
        );
        peditregLayout.setVerticalGroup(
            peditregLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peditregLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pdashboad.add(peditreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 361, 50));

        ppar.setBackground(new java.awt.Color(225, 221, 221));
        ppar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pparMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pparMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon9.png"))); // NOI18N
        jLabel5.setText("Parents");

        javax.swing.GroupLayout pparLayout = new javax.swing.GroupLayout(ppar);
        ppar.setLayout(pparLayout);
        pparLayout.setHorizontalGroup(
            pparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pparLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel5)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        pparLayout.setVerticalGroup(
            pparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pparLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pdashboad.add(ppar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 361, 50));

        peditpar.setBackground(new java.awt.Color(225, 221, 221));
        peditpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peditparMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                peditparMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon10.png"))); // NOI18N
        jLabel6.setText("Edit Info");

        javax.swing.GroupLayout peditparLayout = new javax.swing.GroupLayout(peditpar);
        peditpar.setLayout(peditparLayout);
        peditparLayout.setHorizontalGroup(
            peditparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peditparLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel6)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        peditparLayout.setVerticalGroup(
            peditparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peditparLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pdashboad.add(peditpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 361, 54));

        pdoc.setBackground(new java.awt.Color(225, 221, 221));
        pdoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdocMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pdocMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon9.png"))); // NOI18N
        jLabel7.setText("Document");

        javax.swing.GroupLayout pdocLayout = new javax.swing.GroupLayout(pdoc);
        pdoc.setLayout(pdocLayout);
        pdocLayout.setHorizontalGroup(
            pdocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdocLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel7)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        pdocLayout.setVerticalGroup(
            pdocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdocLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pdashboad.add(pdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 361, 50));

        peditdoc.setBackground(new java.awt.Color(225, 221, 221));
        peditdoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peditdocMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                peditdocMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon10.png"))); // NOI18N
        jLabel8.setText("Edit Info");

        javax.swing.GroupLayout peditdocLayout = new javax.swing.GroupLayout(peditdoc);
        peditdoc.setLayout(peditdocLayout);
        peditdocLayout.setHorizontalGroup(
            peditdocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peditdocLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel8)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        peditdocLayout.setVerticalGroup(
            peditdocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peditdocLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pdashboad.add(peditdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 361, 50));

        pacset.setBackground(new java.awt.Color(225, 221, 221));
        pacset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pacsetMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pacsetMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon7.png"))); // NOI18N
        jLabel9.setText("Account Settings");

        javax.swing.GroupLayout pacsetLayout = new javax.swing.GroupLayout(pacset);
        pacset.setLayout(pacsetLayout);
        pacsetLayout.setHorizontalGroup(
            pacsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pacsetLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(42, 42, 42))
        );
        pacsetLayout.setVerticalGroup(
            pacsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pacsetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pdashboad.add(pacset, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 360, 70));

        pleave.setBackground(new java.awt.Color(225, 221, 221));
        pleave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pleaveMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pleaveMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon9.png"))); // NOI18N
        jLabel10.setText("Leaved Children info");

        javax.swing.GroupLayout pleaveLayout = new javax.swing.GroupLayout(pleave);
        pleave.setLayout(pleaveLayout);
        pleaveLayout.setHorizontalGroup(
            pleaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pleaveLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel10)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pleaveLayout.setVerticalGroup(
            pleaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pleaveLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pdashboad.add(pleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 361, 50));

        peditlea.setBackground(new java.awt.Color(225, 221, 221));
        peditlea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peditleaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                peditleaMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon10.png"))); // NOI18N
        jLabel11.setText("Edit Info");

        javax.swing.GroupLayout peditleaLayout = new javax.swing.GroupLayout(peditlea);
        peditlea.setLayout(peditleaLayout);
        peditleaLayout.setHorizontalGroup(
            peditleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peditleaLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(78, 78, 78))
        );
        peditleaLayout.setVerticalGroup(
            peditleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pdashboad.add(peditlea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 361, 50));

        psearch.setBackground(new java.awt.Color(225, 221, 221));
        psearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psearchMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psearchMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si.png"))); // NOI18N
        jLabel12.setText("Search");

        javax.swing.GroupLayout psearchLayout = new javax.swing.GroupLayout(psearch);
        psearch.setLayout(psearchLayout);
        psearchLayout.setHorizontalGroup(
            psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psearchLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        psearchLayout.setVerticalGroup(
            psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psearchLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pdashboad.add(psearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 361, 50));

        getContentPane().add(pdashboad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 840));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1300, 970));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ldashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ldashMouseClicked

        active();
    }//GEN-LAST:event_ldashMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        nonactive();
       // pmain.add(reg).setVisible(true);
        
    }//GEN-LAST:event_formMouseClicked

    private void peditdocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peditdocMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Clickedcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
          
    }//GEN-LAST:event_peditdocMousePressed

    private void pdocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdocMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Clickedcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
    }//GEN-LAST:event_pdocMousePressed

    private void peditparMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peditparMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Clickedcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
    }//GEN-LAST:event_peditparMousePressed

    private void pacsetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacsetMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Clickedcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
    }//GEN-LAST:event_pacsetMousePressed

    private void pparMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pparMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Clickedcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
    }//GEN-LAST:event_pparMousePressed

    private void peditregMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peditregMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Clickedcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
    }//GEN-LAST:event_peditregMousePressed

    private void pregMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pregMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Clickedcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
    }//GEN-LAST:event_pregMousePressed

    private void phomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phomeMousePressed

        phome.setBackground(Clickedcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
    }//GEN-LAST:event_phomeMousePressed

    private void pregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pregMouseClicked

        
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(reg).setVisible(true);
    }//GEN-LAST:event_pregMouseClicked

    private void peditregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peditregMouseClicked

        editreg er=new editreg();
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(er).setVisible(true);
        
    }//GEN-LAST:event_peditregMouseClicked

    private void pparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pparMouseClicked

        parents p=new parents();
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(p).setVisible(true);
    }//GEN-LAST:event_pparMouseClicked

    private void peditparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peditparMouseClicked

        editpar ep=new editpar();
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(ep).setVisible(true);
    }//GEN-LAST:event_peditparMouseClicked

    private void phomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phomeMouseClicked

        pmain.removeAll();
        pmain.repaint();
        pmain.add(in).setVisible(true);
        
    }//GEN-LAST:event_phomeMouseClicked

    private void pdocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdocMouseClicked

        document doc=new document();
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(doc).setVisible(true);
    }//GEN-LAST:event_pdocMouseClicked

    private void peditdocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peditdocMouseClicked

        editdoc ed=new editdoc();
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(ed).setVisible(true);
    }//GEN-LAST:event_peditdocMouseClicked

    private void pacsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacsetMouseClicked

        acset ac=new acset();
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(ac).setVisible(true);
    }//GEN-LAST:event_pacsetMouseClicked

    private void pleaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pleaveMouseClicked

          Leaveinfo li=new Leaveinfo();
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(li).setVisible(true);
    }//GEN-LAST:event_pleaveMouseClicked

    private void pleaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pleaveMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Clickedcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Defaultcolor);
    }//GEN-LAST:event_pleaveMousePressed

    private void peditleaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peditleaMouseClicked

        editlev lv=new editlev();
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(lv).setVisible(true);
    }//GEN-LAST:event_peditleaMouseClicked

    private void peditleaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peditleaMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Clickedcolor);
        psearch.setBackground(Defaultcolor);
    }//GEN-LAST:event_peditleaMousePressed

    private void psearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psearchMouseClicked

        search sc=new search();
        
        pmain.removeAll();
        pmain.repaint();
        pmain.add(sc).setVisible(true);
    }//GEN-LAST:event_psearchMouseClicked

    private void psearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psearchMousePressed

        phome.setBackground(Defaultcolor);
        preg.setBackground(Defaultcolor);
        ppar.setBackground(Defaultcolor);
        pdoc.setBackground(Defaultcolor);
        peditreg.setBackground(Defaultcolor);
        peditpar.setBackground(Defaultcolor);
        peditdoc.setBackground(Defaultcolor);
        pacset.setBackground(Defaultcolor);
        pleave.setBackground(Defaultcolor);
        peditlea.setBackground(Defaultcolor);
        psearch.setBackground(Clickedcolor);
    }//GEN-LAST:event_psearchMousePressed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked

        Login log=new Login();
        
        log.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ldash;
    private javax.swing.JPanel pacset;
    private javax.swing.JPanel pdashboad;
    private javax.swing.JPanel pdoc;
    private javax.swing.JPanel peditdoc;
    private javax.swing.JPanel peditlea;
    private javax.swing.JPanel peditpar;
    private javax.swing.JPanel peditreg;
    private javax.swing.JPanel phome;
    private javax.swing.JPanel pleave;
    private javax.swing.JPanel pmain;
    private javax.swing.JPanel ppar;
    private javax.swing.JPanel preg;
    private javax.swing.JPanel psearch;
    // End of variables declaration//GEN-END:variables
}
