
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        pmainlog.add(pic).setVisible(true);
    }

    Home home=new Home();
    Fogetpassword fp=new Fogetpassword();
    loginpic pic=new loginpic();
    
    
    int y=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbforget = new javax.swing.JLabel();
        txtun = new javax.swing.JTextField();
        txtpw = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        lbprofile = new javax.swing.JLabel();
        bclear = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        blogin = new javax.swing.JButton();
        cb_show = new javax.swing.JCheckBox();
        pmainlog = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        plogin.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN TO YOUR ACCOUT");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Name");

        lbforget.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbforget.setForeground(new java.awt.Color(255, 255, 255));
        lbforget.setText("Forget Password");
        lbforget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbforgetMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("WELCOME");

        bclear.setBackground(new java.awt.Color(255, 255, 255));
        bclear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        bclear.setForeground(new java.awt.Color(0, 51, 102));
        bclear.setText("RESET");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });

        bexit.setBackground(new java.awt.Color(255, 255, 255));
        bexit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        bexit.setForeground(new java.awt.Color(0, 51, 102));
        bexit.setText("EXIT");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        blogin.setBackground(new java.awt.Color(255, 255, 255));
        blogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        blogin.setForeground(new java.awt.Color(0, 51, 102));
        blogin.setText("LOGIN");
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });

        cb_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/show.png"))); // NOI18N
        cb_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ploginLayout = new javax.swing.GroupLayout(plogin);
        plogin.setLayout(ploginLayout);
        ploginLayout.setHorizontalGroup(
            ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ploginLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ploginLayout.createSequentialGroup()
                        .addComponent(blogin)
                        .addGap(34, 34, 34)
                        .addComponent(bclear)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ploginLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75))))
            .addGroup(ploginLayout.createSequentialGroup()
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ploginLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ploginLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29))))
                    .addGroup(ploginLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbforget)
                            .addGroup(ploginLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ploginLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtun)
                            .addComponent(txtpw, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_show)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ploginLayout.setVerticalGroup(
            ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ploginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ploginLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(128, 128, 128)
                        .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bclear)
                            .addComponent(blogin))
                        .addGap(43, 43, 43)
                        .addComponent(lbforget)
                        .addGap(18, 18, 18)
                        .addComponent(bexit)
                        .addGap(81, 81, 81))
                    .addGroup(ploginLayout.createSequentialGroup()
                        .addComponent(txtun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_show, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtpw))
                        .addGap(346, 346, 346))))
        );

        pmainlog.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pmainlogLayout = new javax.swing.GroupLayout(pmainlog);
        pmainlog.setLayout(pmainlogLayout);
        pmainlogLayout.setHorizontalGroup(
            pmainlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        pmainlogLayout.setVerticalGroup(
            pmainlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pmainlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pmainlog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbforgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbforgetMouseClicked

               
         pmainlog.add(fp).setVisible(true);
         pmainlog.add(pic).setVisible(true);
    }//GEN-LAST:event_lbforgetMouseClicked

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed

     if( JOptionPane.showConfirmDialog(this,"Do you want to Eixt?","EXIT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0);
      }
    }//GEN-LAST:event_bexitActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

         pmainlog.add(fp).setVisible(false);
         pmainlog.add(pic).setVisible(true);
    }//GEN-LAST:event_formMouseClicked

    
    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed

       txtun.setText("");
       txtpw.setText("");
        
                  
        
    }//GEN-LAST:event_bclearActionPerformed

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed

        String xpw= txtpw.getText(); 
        String xun= txtun.getText();
         byte[] person_image=null;
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/children_info_system","root","");
          String sql="select username,password from login where username=? and password=? ";
          
          PreparedStatement st=con.prepareStatement(sql);
          
          st.setString(1, xun);
          st.setString(2, xpw);
         
          
          ResultSet rs=st.executeQuery();
          
   
          
             if(rs.next()){
              String user=rs.getString("username");
              String pass=rs.getString("Password");
              
              
              if(xun.equals(user) && xpw.equals(pass)){
                  home.setVisible(true);
                  this.setVisible(false);
                  
                  
              }
          } else {
                
                  JOptionPane.showMessageDialog(null,"Sorry your Username or Password Incorrect\n Please try again... ");
                  txtun.setText("");
                  txtpw.setText("");
                  
                  y++;
                   
                  if(y==3){
                      
                      txtun.setEditable(false);
                      txtpw.setEnabled(false);
                    JOptionPane.showMessageDialog(null,"Sorry... Your three Attempted failure"+"System Blocked","User Alert",JOptionPane.WARNING_MESSAGE);
              }
             
          
      }
            
        }
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(null,"error while establishing connection\n"+ex);
        }
    }//GEN-LAST:event_bloginActionPerformed

    private void cb_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_showActionPerformed

        if(cb_show.isSelected()){
            
            txtpw.setEchoChar((char)0);
        }
        else{
            
            txtpw.setEchoChar('*');
        }
        
    }//GEN-LAST:event_cb_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bclear;
    private javax.swing.JButton bexit;
    private javax.swing.JButton blogin;
    private javax.swing.JCheckBox cb_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbforget;
    private javax.swing.JLabel lbprofile;
    private javax.swing.JPanel plogin;
    private javax.swing.JPanel pmainlog;
    private javax.swing.JPasswordField txtpw;
    private javax.swing.JTextField txtun;
    // End of variables declaration//GEN-END:variables
}
