
import java.awt.FileDialog;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
public class registration extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0,0));
        BasicInternalFrameUI bui=(BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
       autoid();
       
    }

      static String filename;
      byte[] person_image=null;
      private byte[] picture;
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_cid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rmale = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cb_grade = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_year = new javax.swing.JTextField();
        Attach = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbimage = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txt_birthdate = new javax.swing.JTextField();
        txt_joindate = new javax.swing.JTextField();

        setBorder(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Registration of New Child");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Child ID");
        jLabel2.setInheritsPopupMenu(false);

        txt_cid.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Full Name");
        jLabel3.setInheritsPopupMenu(false);

        txt_cname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Gender");
        jLabel4.setInheritsPopupMenu(false);

        rmale.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        rmale.setText("Male");

        rfemale.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        rfemale.setText("Female");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Date of Birth");
        jLabel5.setInheritsPopupMenu(false);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Address");
        jLabel6.setInheritsPopupMenu(false);

        txt_address.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("Grade");
        jLabel7.setInheritsPopupMenu(false);

        cb_grade.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cb_grade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select the Grade", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("Date of Join");
        jLabel8.setInheritsPopupMenu(false);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setText("Remark");
        jLabel9.setInheritsPopupMenu(false);

        txt_remark.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("Year");
        jLabel11.setInheritsPopupMenu(false);

        txt_year.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        txt_year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_yearKeyTyped(evt);
            }
        });

        Attach.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Attach.setText("Attach Photo");
        Attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbimage.setBackground(new java.awt.Color(204, 204, 255));
        lbimage.setForeground(new java.awt.Color(102, 0, 51));
        lbimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbimageMouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_remark, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_joindate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rmale)
                                .addGap(32, 32, 32)
                                .addComponent(rfemale))
                            .addComponent(txt_cname, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cid, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Attach)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jButton3)))
                                .addContainerGap(149, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbimage, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_cid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_cname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(85, 85, 85))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rmale)
                                    .addComponent(rfemale))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lbimage, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Attach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txt_joindate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_remark, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton3))
                .addGap(169, 169, 169))
        );

        setBounds(30, 2, 818, 649);
    }// </editor-fold>//GEN-END:initComponents

    
   public void autoid(){
            try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/children_info_system","root","");
        
        String sql="select child_id from children order by child_id desc limit 1";
        PreparedStatement pst=con.prepareStatement(sql);
        ResultSet rs=pst.executeQuery();
        
       
        //rs.getString("child_id");
        
        if(rs.next())
        {
            String rid=rs.getString("child_id");
            int co=rid.length();
            String txt=rid.substring(0,3);
            String no=rid.substring(3,co);
            int n=Integer.parseInt(no);
            n++;
            String sno=Integer.toString(n);
            String fid=txt+sno;
            txt_cid.setText(fid);
            
            
        }
        else{
            
            
            txt_cid.setText("HOH10001");
            
            
        }
        
    }

catch(Exception ex){

    JOptionPane.showMessageDialog(null,"hi hello"+ex);
}
}
    
   
        
        
   
    
    private void AttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachActionPerformed

        /*JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File fl=chooser.getSelectedFile();
        Image getAbsolutePath=null;
        filename=fl.getAbsolutePath();
        ImageIcon icon=new ImageIcon(filename);
        Image image=icon.getImage().getScaledInstance(lbimage.getWidth(),lbimage.getHeight(),Image.SCALE_SMOOTH);
        lbimage.setIcon(icon);*/
        
         JFileChooser chooser=new JFileChooser();
         chooser.showOpenDialog(null);
         File f=chooser.getSelectedFile();
         filename=f.getAbsolutePath();
         ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbimage.getWidth(),lbimage.getHeight(),Image.SCALE_SMOOTH));
         lbimage.setIcon(imageIcon);
         
       try{
           
          File image=new File(filename);
          FileInputStream fis=new FileInputStream(image);
          ByteArrayOutputStream bos=new ByteArrayOutputStream();
          byte[] buf=new byte[1024];
          for (int readNum;(readNum=fis.read(buf))!=-1;){
              bos.write(buf,0,readNum);
          }
          person_image=bos.toByteArray();
          
       }   
       catch(Exception ex){
           
           JOptionPane.showMessageDialog(null,ex);
       }
       
        
        
        
    }//GEN-LAST:event_AttachActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try{
            
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/children_info_system","root","");
           
           String sql="insert into children(child_id,child_name,gender,dob,address,grade,date_of_join,year,image,remark) values (?,?,?,?,?,?,?,?,?,?)";
           PreparedStatement pst=con.prepareStatement(sql);
           
           pst.setString(1,txt_cid.getText() );
           pst.setString(2,txt_cname.getText());
           
           String gender = null;
           if(rmale.isSelected()){
               
               gender="Male";
           }
           if(rfemale.isSelected()){
               
               gender="Female";
           }
           
           pst.setString(3,gender);
           
           pst.setString(4, txt_birthdate.getText());
          /* SimpleDateFormat sdf=new SimpleDateFormat("YYYY-MM-DD");
           String date=sdf.format(dc_birth.getDate());
           pst.setString(4,date);*/
           
           pst.setString(5,txt_address.getText());
           
           String grade = null;
           if(cb_grade.getSelectedIndex()==0){
               
               JOptionPane.showMessageDialog(null,"Grade cannot be Selected...\nPlease Select Related Grade Option");
           }
           if(cb_grade.getSelectedIndex()==1){
               
               grade="1";
           }
           if(cb_grade.getSelectedIndex()==2){
               
               grade="2";
           }
           if(cb_grade.getSelectedIndex()==3){
               
               grade="3";
           }
           if(cb_grade.getSelectedIndex()==4){
               
               grade="4";
           }
           if(cb_grade.getSelectedIndex()==5){
               
               grade="5";
           }
           if(cb_grade.getSelectedIndex()==6){
               
               grade="6";
           }
           if(cb_grade.getSelectedIndex()==7){
               
               grade="7";
           }
           if(cb_grade.getSelectedIndex()==8){
               
               grade="8";
           }
           if(cb_grade.getSelectedIndex()==9){
               
               grade="9";
           }
           if(cb_grade.getSelectedIndex()==10){
               
               grade="10";
           }
           if(cb_grade.getSelectedIndex()==11){
               
               grade="11";
           }
           if(cb_grade.getSelectedIndex()==12){
               
               grade="12";
           }
           if(cb_grade.getSelectedIndex()==13){
               
               grade="13";
           }
           pst.setString(6,grade);
      
           pst.setString(7,txt_joindate.getText());
           /*String date1=sdf.format(dc_join.getDate());
           pst.setString(7,date);*/
           
           pst.setString(8,txt_year.getText());
           pst.setBytes(9,person_image);
           pst.setString(10,txt_remark.getText());
           
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null,"Successfully submited");
                clearc();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lbimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbimageMouseClicked

      
        
    }//GEN-LAST:event_lbimageMouseClicked

    public void clearc(){
        
        txt_cid.setText("");
        txt_cname.setText("");
        rmale.setSelected(false);
        rfemale.setSelected(false);
        txt_birthdate.setText("");
        //dc_birth.setDate(null);
        txt_address.setText("");
        cb_grade.setSelectedIndex(0);
       // dc_join.setDate(null);
        txt_joindate.setText("");
        txt_year.setText("");
        txt_remark.setText("");
        lbimage.setIcon(null);
             
        }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        clearc();
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_yearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_yearKeyTyped

        
       
    }//GEN-LAST:event_txt_yearKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attach;
    private javax.swing.JComboBox cb_grade;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbimage;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_birthdate;
    private javax.swing.JTextField txt_cid;
    private javax.swing.JTextField txt_cname;
    private javax.swing.JTextField txt_joindate;
    private javax.swing.JTextField txt_remark;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
